# Generated by Django 5.2.3 on 2025-06-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена (большой)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_medium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена (средний)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, help_text='Например: 250 мл', max_length=50, verbose_name='Объем (основной)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_large',
            field=models.CharField(blank=True, help_text='Например: 450 мл', max_length=50, verbose_name='Объем (большой)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_medium',
            field=models.CharField(blank=True, help_text='Например: 350 мл', max_length=50, verbose_name='Объем (средний)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена (основная)'),
        ),
    ]
